### ISSUE TITLE
man page has wrong file name

### ISSUE THREAD

**Issue by uffejakobsen** [dlenski/gp-saml-gui#25]
The man page is named "gp-saml-gui.8" (using hypens as separators)

But recently the command has switched name to "gp_saml_gui.py" (using underscores as separators)

**Comment by dlenski** [comment]
:thinking: 

Although the _source file_ is now called `gp_saml_gui.py` (so that it can be used as a Python module name), the name of the installed shell command is [still `gp-saml-gui`](https://github.com/dlenski/gp-saml-gui/blob/master/setup.py#L24), right?

**Comment by uffejakobsen** [comment]
argh - I missed that point - I usually just grab the source file and copy it to a folder of my choice.
I'll close this issue right awway. Sorry about that :-)
