### ISSUE TITLE
Code throws up errors

### ISSUE THREAD

**Issue by maitra** [dlenski/gp-saml-gui#3]
Hello, I am trying to connect using the commands given, and I get:
```
 $eval $( ./gp-saml-gui.py -v vpn.iastate.edu )
Traceback (most recent call last):
  File "./gp-saml-gui.py", line 127, in <module>
    xml = ET.fromstring(res.content)
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 7, column 2

```
There is some error that I do not quite understand. Am I msissing some dependencies? I am on Fedora 30.

**Comment by dlenski** [comment]
Hmmm… it's having trouble parsing the `prelogin.esp` response from your VPN. That's strange. I've never seen a real GP VPN that doesn't respond with valid XML.

Can you share the XML contents of the `prelogin.esp` response from your VPN?

**Comment by dlenski** [comment]
Apparently it's https://vpn.iastate.edu … going to that page reveals it to obviously be a Cisco AnyConnect VPN… **not** a PAN GlobalProtect VPN.

This tool is not relevant or intended for use with non-GP VPNs.

**Comment by maitra** [comment]
Is there any advice or pointers on how to modify for AnyConnect?
