### ISSUE TITLE
extra commands not properly parsed/passed

### ISSUE THREAD

**Issue by jdbarnes-isi** [dlenski/gp-saml-gui#33]
```
$ ./gp_saml_gui.py -P --gateway --clientos="Linux" host.vpn.net --pfs
usage: gp_saml_gui.py [-h] [--no-verify] [-C COOKIES | -K] [-g | -p] [-c CERT] [--key KEY] [-v | -q] [-x | -P | -S] [-u] [--clientos {Mac,Linux,Windows}] [-f EXTRA] server [openconnect_extra ...]
gp_saml_gui.py: error: unrecognized arguments: --pfs

$ ./gp_saml_gui.py -P --gateway --clientos="Linux" host.vpn.net --csd-wrapper=/usr/libexec/openconnect/hipreport.sh
usage: gp_saml_gui.py [-h] [--no-verify] [-C COOKIES | -K] [-g | -p] [-c CERT] [--key KEY] [-v | -q] [-x | -P | -S] [-u] [--clientos {Mac,Windows,Linux}] [-f EXTRA] server [openconnect_extra ...]
gp_saml_gui.py: error: unrecognized arguments: --csd-wrapper=/usr/libexec/openconnect/hipreport.sh

```

writing the command as: 
`./gp_saml_gui.py -P --gateway --clientos="Linux" host.vpn.net \ --csd-wrapper=/usr/libexec/openconnect/hipreport.sh`
enters the saml handshake phase, but once openconnect command is generated, it is generated as

```

Launching OpenConnect with pkexec, equivalent to:
    echo CookieTextHere |
        sudo openconnect --protocol=gp --user=user@fq.dn --os=linux-64 --usergroup=gateway:prelogin-cookie --passwd-on-stdin host.vpn.net ' --csd-wrapper=/usr/libexec/openconnect/hipreport.sh'
```
which causes openconnect to fail like so:
```
Too many arguments on command line
Usage:  openconnect [options] <server>
Open client for multiple VPN protocols, version v8.10-6.fc34
```

So, I suppose I could be doing something incorrectly, or not reading something correctly. If there's a way that I can solve this problem without asking you to change code, please let me know.

I naively tried to move `openconnect_extra` into the openconnect_args array, but got some kind of python list/string conversion error.

**Comment by dlenski** [comment]
You need to put `--` before the extra arguments for OpenConnect, so that they aren't misinterpreted as arguments for `gp-saml-gui` itself.

As shown in the README:

![image](https://user-images.githubusercontent.com/128716/139730581-d5b783ee-fa74-44ae-8344-5752194b4310.png)

**Comment by jdbarnes-isi** [comment]
Thanks that was my bad. I was pretty sure I had tried that and it didn't work, but perhaps I fat fingered something dumb so was red herring'ed down a stupid path w/ regard to what exactly to put in the CL args.

I probably read the example wrongly, and thought the code block had something to do with polkit or sudo access since I was skimming quickly instead of really paying attention.

Sorry about that, and thanks for the clarification.
