### ISSUE TITLE
$ gp-saml-gui command not valid after gp-saml-gui install

### ISSUE THREAD

**Issue by philippulus** [dlenski/gp-saml-gui#34]
Don't come any farther than with the '$ gp-saml-gui' command.
It is not valid.

$ pip3 install https://github.com/dlenski/gp-saml-gui/archive/master.zip
Collecting https://github.com/dlenski/gp-saml-gui/archive/master.zip
Downloading https://github.com/dlenski/gp-saml-gui/archive/master.zip
- 164 kB 175 kB/s
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (from gp-saml-gui==0.1) (3.36.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from gp-saml-gui==0.1) (2.22.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject->gp-saml-gui==0.1) (1.16.2)
Building wheels for collected packages: gp-saml-gui
Building wheel for gp-saml-gui (setup.py) ... done
Created wheel for gp-saml-gui: filename=gp_saml_gui-0.1-py3-none-any.whl size=22563 sha256=b55dafecbba7a98bc15f2956cc1de8d035a036324816dc54a4f6813829fdb877
Stored in directory: /tmp/pip-ephem-wheel-cache-aa1pi5st/wheels/e2/0f/fd/0fe4e06555dce4a18ca14842b18d0f07c8fba37c309af8695e
Successfully built gp-saml-gui
Installing collected packages: gp-saml-gui
WARNING: The script gp-saml-gui is installed in '/home/nicolas/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed gp-saml-gui-0.1

$ gp-saml-gui
gp-saml-gui: command not found
$ usage: gp-saml-gui [-h] [--no-verify] [-C COOKIES | -K] [-p | -g] [-c CERT]
-K]: command not found
-g]: command not found
usage:: command not found
$ [--key KEY] [-v | -q] [-x | -P | -S] [-u]
-P: command not found
-S]: command not found
-q]: command not found
[--key: command not found
$ [--clientos {Windows,Linux,Mac}] [-f EXTRA]
[--clientos: command not found
$ server [openconnect_extra [openconnect_extra ...]]
Defaulting to port 8080Listening on port 8080

**Comment by Segfavlt** [comment]
You need to add $HOME/.local/bin to your $PATH, as said in the warning message from pip.
