### ISSUE TITLE
SSL certificate error with 4096-bit certificates

### ISSUE THREAD

**Issue by hwaterer** [dlenski/gp-saml-gui#46]
Hi Daniel,

I recently started getting the SSL certificate error "unable to get local issuer certificate". I'm told that the old 2048-bit certificates were renewed as 4096-bit certificates. Could the change of encryption be causing this problem?

Thanks,
Hamish

**Comment by dlenski** [comment]
Seems extremely unlikely that the *size* of the certs has anything to do with this.

More likely, something is different about the new certs, such as being signed by a different CA which your system doesn't trust.

Can you show a more detailed error output?

**Comment by hwaterer** [comment]
gp-saml-gui: error: SSL certificate error (try --no-verify to ignore): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

**Comment by dlenski** [comment]
Yes, this means that the cert's issuer is untrusted. Presumably the root/CA has changed from the new one to the old one.

Did you try `--no-verify` to just ignore it? (Which is insecure)

**Comment by hwaterer** [comment]
They don't seem to think that there's a problem with the certificates, but I'll keep trying.

Yes, I can get everything to work using the --no-verify option.

Thanks.

**Comment by dlenski** [comment]
> They don't seem to think that there's a problem with the certificates, but I'll keep trying.

It's not a "problem" with the certificates _per se_; it's (likely) a problem with your system not having the root certificates to verify them.

Without knowing any details of the specific certs (or the OS you're using, etc) it's basically impossible for me to speculate. Use https://crt.sh/?q=YOUR.DOMAIN.NAME for an online analyzer, or https://www.ssllabs.com/ssltest/analyze.html?d=YOUR.DOMAIN.NAME for a more extensive one, or [`certtool -i < your_cert_file`](https://man7.org/linux/man-pages/man1/certtool.1.html) for an offline tool.

**Comment by hwaterer** [comment]
Ha! Thank you!

https://crt.sh/?q=YOUR.DOMAIN.NAME reports "Certificates: None found"
https://www.ssllabs.com/ssltest/analyze.html?d=YOUR.DOMAIN.NAME reports "This server's certificate chain is incomplete."

I'll send this information to the powers that be.

**Comment by hwaterer** [comment]
Ha! Thank you!

https://crt.sh/?q=YOUR.DOMAIN.NAME reports "Certificates: None found"
https://www.ssllabs.com/ssltest/analyze.html?d=YOUR.DOMAIN.NAME reports "This server's certificate chain is incomplete."

I sent this to the powers that be and they fixed the issue. Thanks again.
