### ISSUE TITLE
Microsoft SAML contains XML in comment

### ISSUE THREAD

**Issue by Ericson2314** [dlenski/gp-saml-gui#79]
I get a page that says `Login Successful!` and inspecting the DOM (if I go to the URL manually) shows roughly:

```html
<html>
  <head></head>
  <body>Login Successful!</body
  <!--
    <saml-auth-status>1</saml-auth-status>
    <prelogin-cookie>REDACTEDBAASE64==</prelogin-cookie>
    <saml-username>READACTEDUSERNAME/saml-username>
    <saml-slo>yes</saml-slo>
    <saml-SessionNotOnOrAfter></saml-SessionNotOnOrAfter>
  -->
</html>
````
`gp-saml-gui` doesn't seem to know how to parse this; the browser window is still open waiting for me to do more things, but there is no button to press.

**Comment by dlenski** [comment]
> gp-saml-gui doesn't seem to know how to parse this;

Hmmm, thanks to #59, `gp-saml-gui` _is supposed to know how to parse this_.

Are you running an old version? If so, upgrade.

Are you running a version that includes #59? If so, run `gp-saml-gui -vv` (`--verbose` × 2!) and give us more details.

**Comment by Ericson2314** [comment]
I'll double check the version, sorry about that.

**Comment by Ericson2314** [comment]
Yup, the newer version works like a charm. Afterwords I do get an `openconnec`t error, but that's not this project's fault. Thank you!

I will update the version packaged in Nixpkgs so others do not have this issue :). Does this project have version numbers or does one just grab the latest commit off master?

**Comment by dlenski** [comment]
> Does this project have version numbers or does one just grab the latest commit off master?

[No](https://github.com/dlenski/gp-saml-gui/blob/master/setup.py#L13), no releases [or tags](https://github.com/dlenski/gp-saml-gui/tags) yet.
