### ISSUE TITLE
Hook up openconnect's  --script

### ISSUE THREAD

**Issue by arichiardi** [dlenski/gp-saml-gui#9]
Hi there!

I stumbled upon this nice little script cause in my company we are moving to SAML login.

One thing that I had in my previous `openconnect` setup was:

```
--script="$vpn_slice_bin --verbose $my_tunneled_domains
```

I wonder if you are open to a contribution that adds a parameter, say `--openconnect-script` option to be able to forward the above down to `openconnect`.

Thanks for this and please let me know your thoughts!

**Comment by dlenski** [comment]
OpenConnect's `--script` is for routing configuration. This is for authentication.

They are entirely separate.

Besides, there is already a compact way to use this script to pass authentication results into `openconnect` given in the docs, as a drop-in replacement for `openconnect --authenticate`:

```
eval $( gp-saml-gui.py --clientos=Windows vpn.company.com ) && echo "$COOKIE" | openconnect --protocol=gp -u "$USER" --os="$OS" --passwd-on-stdin "$HOST"
```

**Comment by arichiardi** [comment]
> OpenConnect's --script is for routing configuration. This is for authentication.

I see I completely misread that usage - sorry about that, closing this one.

**Comment by dlenski** [comment]
Thanks to #16, `gp-saml-gui.py` now has the option to "just automatically invoke OpenConnect by itself."
