### ISSUE TITLE
Need to pass --csd-wrapper=(wrapper) command-line argument

### ISSUE THREAD

**Issue by aaronw2** [dlenski/gp-saml-gui#95]
I need to be able to pass --csd-wrapper=(wrapper script) to openconnect in order to connect to my employer's VPN. Can the command line pass this through? It's unclear how to do this. I modified my copy of gp_saml_gui.py to do this and it is working well for me.

It might also be nice to put all the needed parameters in a file (i.e. YAML) and just read the parameters from there instead of requiring a bunch of command-line options.

**Comment by dlenski** [comment]
> Can the command line pass this through? It's unclear how to do this.

Yes, it passes any/all extra arguments to OpenConnect. Just put `--` by itself before the extra arguments for OpenConnect so that they're detected as separate.

```
gp-saml-gui REGULAR ARGUMENTS -- --csd-wrapper=whatever
````

As the usage shows:
```
usage: gp-saml-gui [-h] [--no-verify] [-C COOKIES | -K] [-g | -p] [-c CERT]
                      [--key KEY] [-v | -q] [-x | -P | -S] [-u]
                      [--clientos {Mac,Windows,Linux}] [-f EXTRA]
                      [--allow-insecure-crypto] [--user-agent USER_AGENT]
                      server [openconnect_extra [openconnect_extra ...]]
```
